//
//          File:   TUIStatus+Spinner.swift
//    Created by:   African Swift

import Darwin

public extension TUIStatus.Spinners
{
  public static let dots = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
  public static let dots2 = "⣾⣽⣻⢿⡿⣟⣯⣷"
  public static let dots3 = "⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓"
  public static let dots4 = "⠄⠆⠇⠋⠙⠸⠰⠠⠰⠸⠙⠋⠇⠆"
  public static let dots5 = "⠋⠙⠚⠒⠂⠂⠒⠲⠴⠦⠖⠒⠐⠐⠒⠓⠋"
  public static let dots6 = "⠁⠉⠙⠚⠒⠂⠂⠒⠲⠴⠤⠄⠄⠤⠴⠲⠒⠂⠂⠒⠚⠙⠉⠁"
  public static let dots7 = "⠈⠉⠋⠓⠒⠐⠐⠒⠖⠦⠤⠠⠠⠤⠦⠖⠒⠐⠐⠒⠓⠋⠉⠈"
  public static let dots8 = "⠁⠁⠉⠙⠚⠒⠂⠂⠒⠲⠴⠤⠄⠄⠤⠠⠠⠤⠦⠖⠒⠐⠐⠒⠓⠋⠉⠈⠈"
  public static let dots9 = "⢹⢺⢼⣸⣇⡧⡗⡏"
  public static let dots10 = "⢄⢂⢁⡁⡈⡐⡠"
  public static let dots11 = "⠁⠂⠄⡀⢀⠠⠐⠈"
  public static let line = "-\\|/"
  public static let line2 = "⠂-–—–-"
  public static let pipe = "┤┘┴└├┌┬┐"
  public static let star = "✶✸✹✺✹✷"
  public static let star2 = "+x*"
  public static let flip = "___-``'´-___"
  public static let hamburger = "☱☲☴"
  public static let growUp = "▁▃▄▅▆▇"
  public static let growDown = "▇▆▅▄▃▁"
  public static let upDown = "▁▃▄▅▆▇▆▅▄▃"
  public static let growHorizontal = "▏▎▍▌▋▊▉▊▋▌▍▎"
  public static let balloon = " .oO@* "
  public static let balloon2 = ".oO°Oo."
  public static let noise = "▓▒░"
  public static let bounce = "⠁⠂⠄⠂"
  public static let boxBounce = "▖▘▝▗"
  public static let boxBounce2 = "▌▀▐▄"
  public static let triangle = "◢◣◤◥"
  public static let arc = "◜◠◝◞◡◟"
  public static let circle = "◡⊙◠"
  public static let squareCorners = "◰◳◲◱"
  public static let circleQuarters = "◴◷◶◵"
  public static let circleHalves = "◐◓◑◒"
  public static let squish = "╫╪"
  public static let toggle = "⊶⊷"
  public static let toggle2 = "▫▪"
  public static let toggle3 = "□■"
  public static let toggle4 = "■□▪▫"
  public static let toggle5 = "▮▯"
  public static let toggle6 = "ဝ၀"
  public static let toggle7 = "⦾⦿"
  public static let toggle8 = "◍◌"
  public static let toggle9 = "◉◎"
  public static let toggle10 = "㊂㊀㊁"
  public static let toggle11 = "⧇⧆"
  public static let toggle12 = "☗☖"
  public static let toggle13 = "=*-"
  public static let arrow = "←↖↑↗→↘↓↙"
  public static let arrow2 = "⬆️↗️➡️↘️⬇️↙️⬅️↖️"
  public static let smiley = "😄😝"
  public static let monkey = "🙈🙈🙉🙊"
  public static let hearts = "💛💙💜💚❤️"
  public static let clock = "🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚"
  public static let earth = "🌍🌎🌏"
  public static let moon = "🌑🌒🌓🌔🌕🌖🌗🌘"
  public static let runner = "🚶🏃"
}
